kind: Service
apiVersion: v1
metadata:
  name: rancher-ns
spec:
  selector:
    app: greenhouse
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-greenhouse
  namespace: rancher-ns
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      imagePullSecrets:
      - name: rancher-harbor
      containers:
      - name: maven
        image: 10.10.1.148:30002/pipeline/example:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
